#!/usr/bin/env bash
# Installs Nginx web server and configures it to return "Holberton School" at root

# Update and install
apt-get update -y
apt-get install nginx -y

# Allow Nginx through firewall
ufw allow 'Nginx HTTP'

# Create the index page
echo "Holberton School" > /var/www/html/index.html

# Restart Nginx to apply changes
service nginx restart
