#!/usr/bin/env bash
# Installs Nginx web server and configures it to return "Holberton School" at root

# Update package lists
apt-get update -y

# Install Nginx
apt-get install nginx -y

# Create index page with required content
echo "Holberton School" > /var/www/html/index.html

# Ensure Nginx is running
service nginx restart
